config.set('walk_speed', 100)
config.set('run_speed', 200)
config.set('crouched_speed', 55)
config.set('jump_power', 150)
config.set('command_prefixes', { '/', '!' })
config.set('root_steamid', 'STEAM_0:0:00000000')
config.set('data_save_interval', 60)
config.set('player_data_save_interval', 30)
config.set('respawn_delay', 30)
