Config.set('walk_speed', 100)
Config.set('run_speed', 200)
Config.set('crouched_speed', 55)
Config.set('jump_power', 150)
Config.set('command_prefixes', { '/', '!' })
Config.set('root_steamid', 'STEAM_0:0:00000000')
Config.set('Data.save_interval', 60)
Config.set('player_data_save_interval', 30)
Config.set('respawn_delay', 30)
