--- Environment variables of Flux: the `ENV` table with `getenv` and `setenv`, and the
-- `FLUX_ENV` variable that names the environment Flux runs in.
-- Both entry points of the gamemode include this file first. On the first boot it reads
-- `FLUX_ENV` from `config/environment.local.lua` if that file exists, else from
-- `config/environment.lua`, and falls back to 'development' when the file returns nothing.
-- The server shares variables with clients through `add_client_env`, which appends `setenv`
-- calls to the generated `lua/_flux/environment.lua` file that clients include here.

--
-- Pointers for a C implementation of getenv:
--
-- * All functions must set the ENV global.
-- * The local environment should be copied to the ENV global on fork.
-- * The ENV global should have a __newindex metamethod to set C environment
-- variables if they are changed in the ENV global.
--

AddCSLuaFile()

ENV = ENV or {}

if !getenv then
  --- Gets an environment variable matching the "key" name.
  -- @param key [String variable name]
  -- @param default=nil [Any value to return if the variable is not set]
  -- @return [String environment variable, or default if it is not set]
  function getenv(key, default)
    local res = ENV[key]

    if res != nil then
      return res
    end

    return default
  end
end

if !setenv then
  --- Sets an environment variable "key" to "value".
  -- Will be automatically converted to a string by the C backend.
  -- @param key [String variable name]
  -- @param value [Any new value]
  -- @return [String environment variable reference]
  function setenv(key, value)
    ENV[key] = value
    return ENV[key]
  end
end

do
  local client_vars = {}

  --- Adds an environment variable to the clientside environment variables list.
  -- Can only be used once. Forces key and value to be strings.
  -- @param key [String variable name]
  -- @param value [String variable value]
  function add_client_env(key, value)
    if SERVER and !client_vars[key] then
      client_vars[key] = true
      File.append('lua/_flux/environment.lua', 'setenv("'..tostring(key)..'", "'..tostring(value)..'")\n')
    end
  end
end

if Flux and Flux.initialized then return end

-- Environment stuff
FLUX_ENV_PATH = file.Exists('flux/config/environment.local.lua', 'LUA') and 'flux/config/environment.local.lua' or
  'flux/config/environment.lua'
setenv('FLUX_ENV', string.lower(include(FLUX_ENV_PATH) or 'development'))

if CLIENT then
  include '_flux/environment.lua'
else
  File.write(
    'lua/_flux/environment.lua',
    '--\n-- This file is automatically generated.\n-- Do not edit this file manually!\n--\n\n'
  )
end
