local category = config.create_category('character', 'config.categories.character.title', 'config.categories.character.desc')
category.add_slider('character_min_name_len', 'char_config.min_name_len', 'char_config.min_name_len_desc', { min = 1, max = 256, default = 4 })
category.add_slider('character_max_name_len', 'char_config.max_name_len', 'char_config.max_name_len_desc', { min = 1, max = 256, default = 32 })
category.add_slider('character_min_desc_len', 'char_config.min_desc_len', 'char_config.min_desc_len_desc', { min = 1, max = 1024, default = 32 })
category.add_slider('character_max_desc_len', 'char_config.max_desc_len', 'char_config.max_desc_len_desc', { min = 1, max = 1024, default = 256 })
